In [15]:
# Import libraries

import requests
import json
import pandas as pd

In [16]:
# Set the URL after running api_fase01.py

url = r'http://127.0.0.1:5000/country'

In [17]:
# Import data from API Country

country_data_api = requests.get(url)

In [18]:
# Analyze status and type of data

print(country_data_api.status_code)
print(type(country_data_api.text[:200]))
print(country_data_api.encoding)

200
<class 'str'>
utf-8

In [19]:
# Convert data api in Dict

country_data = json.loads(country_data_api.text)
type(country_data)

dict

In [20]:
# Convert dictionary country_data in DataFrame

df_country = pd.DataFrame.from_dict(country_data, orient='Index')
df_country.head()

,name,currency,population,capital,continent,area
AND,Andorra,EUR,77006,Andorra la Vella,Europe,468.0
ARE,United Arab Emirates,AED,9630959,Abu Dhabi,Asia,82880.0
AFG,Afghanistan,AFN,37172386,Kabul,Asia,647500.0
ATG,Antigua and Barbuda,XCD,96286,St John's,North America,443.0
AIA,Anguilla,XCD,13254,The Valley,North America,102.0

In [21]:
#Manipulation DataFrame

df_country = (
    df_country
    .reset_index()
    .rename(columns={'index': 'Country Code'})
)

df_country.info()
df_country.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Code  250 non-null    object
 1   name          250 non-null    object
 2   currency      250 non-null    object
 3   population    250 non-null    int64
 4   capital       250 non-null    object
 5   continent     250 non-null    object
 6   area          250 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 13.8+ KB

,Country Code,name,currency,population,capital,continent,area
0,AND,Andorra,EUR,77006,Andorra la Vella,Europe,468.0
1,ARE,United Arab Emirates,AED,9630959,Abu Dhabi,Asia,82880.0

In [22]:
#Reading file csv with PIB information

pib = pd.read_csv('../data/raw/gdp_data.csv')
pib.rename(columns={'Country Name': 'name'}, inplace=True)
pib.info()
pib.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            133 non-null    float64
 5   1961            135 non-null    float64
 6   1962            137 non-null    float64
 7   1963            137 non-null    float64
 8   1964            137 non-null    float64
 9   1965            148 non-null    float64
 10  1966            151 non-null    float64
 11  1967            155 non-null    float64
 12  1968            160 non-null    float64
 13  1969            160 non-null    float64
 14  1970            169 non-null    float64
 15  1971            172 non-null    float64
 16  1972            172 non-null    float64
 17  1973            172 non-null    float64
 18  1974            173 non-null    float64
 19  1975            175 non-null    float64
 20  1976            176 non-null    float64
 21  1977            179 non-null    float64
 22  1978            178 non-null    float64
 23  1979            179 non-null    float64
 24  1980            191 non-null    float64
 25  1981            194 non-null    float64
 26  1982            195 non-null    float64
 27  1983            196 non-null    float64
 28  1984            197 non-null    float64
 29  1985            199 non-null    float64
 30  1986            201 non-null    float64
 31  1987            205 non-null    float64
 32  1988            210 non-null    float64
 33  1989            210 non-null    float64
 34  1990            226 non-null    float64
 35  1991            226 non-null    float64
 36  1992            227 non-null    float64
 37  1993            229 non-null    float64
 38  1994            231 non-null    float64
 39  1995            240 non-null    float64
 40  1996            240 non-null    float64
 41  1997            240 non-null    float64
 42  1998            242 non-null    float64
 43  1999            243 non-null    float64
 44  2000            247 non-null    float64
 45  2001            249 non-null    float64
 46  2002            254 non-null    float64
 47  2003            254 non-null    float64
 48  2004            254 non-null    float64
 49  2005            254 non-null    float64
 50  2006            255 non-null    float64
 51  2007            255 non-null    float64
 52  2008            256 non-null    float64
 53  2009            256 non-null    float64
 54  2010            257 non-null    float64
 55  2011            260 non-null    float64
 56  2012            258 non-null    float64
 57  2013            259 non-null    float64
 58  2014            260 non-null    float64
 59  2015            258 non-null    float64
 60  2016            257 non-null    float64
 61  2017            257 non-null    float64
 62  2018            257 non-null    float64
 63  2019            255 non-null    float64
 64  2020            252 non-null    float64
 65  2021            245 non-null    float64
 66  Unnamed: 66     0 non-null      float64
dtypes: float64(63), object(4)
memory usage: 139.4+ KB

,name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129081e+10,2.180870e+10,2.370727e+10,2.821034e+10,2.611906e+10,2.968249e+10,...,9.834729e+11,1.003768e+12,9.245228e+11,8.827213e+11,1.021119e+12,1.007240e+12,1.001017e+12,9.274845e+11,1.080712e+12,NaN

In [25]:
#Manipulation DataFrame

final_csv = pd.merge(df_country, pib, on=['Country Code', 'name'], how='inner')
final_csv.drop(columns=['currency', 'Indicator Name', 'Indicator Code', 'Unnamed: 66'], inplace=True)
final_csv.rename(columns={'Country Code': 'codigo'}, inplace=True)
final_csv.head()

,codigo,name,population,capital,continent,area,1960,1961,1962,1963,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AND,Andorra,77006,Andorra la Vella,Europe,468.0,NaN,NaN,NaN,NaN,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
1,ARE,United Arab Emirates,9630959,Abu Dhabi,Asia,82880.0,NaN,NaN,NaN,NaN,...,3.846101e+11,4.002185e+11,4.141054e+11,3.702755e+11,3.692553e+11,3.905168e+11,4.270494e+11,4.179897e+11,3.494730e+11,4.150216e+11
2,AFG,Afghanistan,37172386,Kabul,Asia,647500.0,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
3,ATG,Antigua and Barbuda,96286,St John's,North America,443.0,NaN,NaN,NaN,NaN,...,1.199948e+09,1.181448e+09,1.249733e+09,1.336693e+09,1.436585e+09,1.467978e+09,1.605944e+09,1.687533e+09,1.370281e+09,1.471126e+09
4,ALB,Albania,2866376,Tirana,Europe,28748.0,NaN,NaN,NaN,NaN,...,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.825579e+10

In [24]:
#Write final data in file csv

final_csv.to_csv('../data/processed/countries_gdp.csv', index=False)